/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package votingApp;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import voting.Voter;

/**
 *
 * @author Mcacisi Sithole
 */
public class Voting_System_App extends javax.swing.JFrame {

    //DECLARE VARIABLES PROGRAM WILL NEED
    private ArrayList <Voter> voteList = new ArrayList<> ();
    private String voter_ID, name, surname, candidate;
    
    
    
    
    /**
     * Creates new form Voting_System_App
     */
    public Voting_System_App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVoterID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        cmbCandidate = new javax.swing.JComboBox<>();
        btnVote = new javax.swing.JToggleButton();
        btnClear = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDisplay = new javax.swing.JTextArea();
        btnExit = new javax.swing.JToggleButton();
        btnRemove = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JToggleButton();
        btnShowVoters = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jlabel1.setText("ENTER YOUR  ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ENTER YOUR NAME(s)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("SURNAME");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("SELECT THE CANDIDATE YOU WISH TO VOTE FOR");

        cmbCandidate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbCandidate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                        CHOOSE YOUR POLITICAL PARTY", "   ANC", "   EFF", "   DA", "   IFP", "   MK PARTY", "   PA", "   FF+", "   UDM", "   PAC", "   ActionSA", "   ACDP", " " }));

        btnVote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVote.setText("VOTE");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("CLEAR_FIELDS");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblDisplay.setEditable(false);
        lblDisplay.setColumns(20);
        lblDisplay.setRows(5);
        jScrollPane1.setViewportView(lblDisplay);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");

        btnSearch.setText("SEARCH");

        btnShowVoters.setText("SHOW VOTERS");
        btnShowVoters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowVotersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(txtVoterID)
                            .addComponent(txtSurname)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVote, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnClear)
                        .addGap(45, 45, 45)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowVoters))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbCandidate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jlabel1)
                            .addComponent(txtVoterID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowVoters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
        castVote();
    }//GEN-LAST:event_btnVoteActionPerformed

    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    
    private void btnShowVotersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowVotersActionPerformed
        displayVoters();
    }//GEN-LAST:event_btnShowVotersActionPerformed

    
    
    
    /*METHODS WITH CODE IMPLEMENTATION TO PRACTISE CLEAN CODE
      CLEAR FIELDS()
      EXIT SYSTEM()
      CAST VOTE()
      SAVE TO FILE()
      RELOAD FROM FILE()
      ADD TO DATABASE()
    */
    private void clear(){
        txtVoterID.setText("");
        txtName.setText("");
        txtSurname.setText("");
        cmbCandidate.setSelectedIndex(0);
    }
    
    
    
    
    
    /*
          GET ALL VARIABLES FROM USER WITH CORRECT DATA NEEDED
          WITH EXCEPTIONAL HANDLING TO PREVENT SYSTEM FROM CRASHING
        */
    private void castVote(){
        
        
    try
       { 
        voter_ID = txtVoterID.getText().trim();
               if(voter_ID.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Please enter your ID NUMBER","Missing data input",JOptionPane.INFORMATION_MESSAGE);
                    return;
               }
               
               Integer.parseInt(voter_ID);
               
       } catch(NumberFormatException e){
              JOptionPane.showMessageDialog(this, "Only Integers are allowed in your\n ID NUMBER", "Incorrect data input", JOptionPane.INFORMATION_MESSAGE);
              return;
       } 
        
        
              
        
        
               
        name = txtName.getText().trim().toUpperCase();
              if(name.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Please enter your NAME","Missing data input",JOptionPane.INFORMATION_MESSAGE);
                    return;
                 } 
              
              
              
              
        surname = txtSurname.getText().trim().toUpperCase();
              if(surname.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Please enter your SURNAME","Missing data input",JOptionPane.INFORMATION_MESSAGE);
                    return;
                 } 
              
              
              
        candidate = (String)cmbCandidate.getSelectedItem();
              if(cmbCandidate.getSelectedIndex() == 0){
                  JOptionPane.showMessageDialog(this, "Please select political party");
                  return;
              }
              
              
              /*
                CREATE A VOTE OBJECT OF THE VOTER.CLASS
                CHECK IF ID ALREADY EXISTS IN VOTE LIST BEFORE YOU ADD A NEW VOTER OBJECT
              */
              
              Voter vote = new Voter(voter_ID,name,surname,candidate);
              
              for(Voter v : voteList){
                  
                  if(v.getVoterID().equals(voter_ID)){
                     JOptionPane.showMessageDialog(this, "Already voted", "Duplicate vote", JOptionPane.INFORMATION_MESSAGE);
                     return;
                  }
              }
              
              
              voteList.add(vote);
              JOptionPane.showMessageDialog(this, "Vote Successfully", "Completed", JOptionPane.PLAIN_MESSAGE);
 
    }
 
    
    
    /*
      A SAVE TO FILE METHOD THAT SERIALIZES THE VOTER CLASS OBJECTS INTO A BINARY FILE
      SAVING VOTERS INTO A BINARY FILE FOR SECURITY PURPOSES AND DATA INTEGRITY
    */
    private void saveToFile(){
        
        
        try
           {
            ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("voters.dat"));
            out.writeObject(voteList);
            JOptionPane.showMessageDialog(this, "Voter added successfully into VOTELIST", "VOTE COMPLETED", JOptionPane.INFORMATION_MESSAGE);
            out.close();
            
           }catch(IOException e){
               JOptionPane.showMessageDialog(this, "Saving not successful", "VOTING_ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           }       
    }
    
    
    
    /*
      DISPLAY METHOD TO CALL THE TEXT AREA AND DISPLAY THE LIST OF PEOPLE WHO ALREADY VOTED
      FOR FASTER PERFORMANCE WE WILL USE THE ARRAYLIST TO DISPLAY 
    */
    private void displayVoters(){
        
        StringBuilder builder = new StringBuilder();
        
        builder.append(String.format("%-15s %-15s %-15s %-15s","VOTER_ID", "NAME", "SURNAME","CANDIDATE" ));
        
        
        lblDisplay.setText(builder.toString());
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voting_System_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voting_System_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voting_System_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voting_System_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voting_System_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JToggleButton btnClear;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnRemove;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JToggleButton btnShowVoters;
    private javax.swing.JToggleButton btnVote;
    private javax.swing.JComboBox<String> cmbCandidate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDisplay;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtVoterID;
    // End of variables declaration//GEN-END:variables
}
